### ISSUE TITLE
int63 values are bound as int64, making them unsigned

### ISSUE THREAD

**Issue by cyberhuman** [ocaml-community/ocaml-mariadb#31]
Since integers are 63-bit in ocaml, the following code does not work properly when trying to bind negative integers:

https://github.com/andrenth/ocaml-mariadb/blob/master/lib/bind.ml#L123

The effect is when trying to bind `-1` to an integer placeholder, it takes the value 2147483647.

**Comment by rr0gi** [comment]
ref #43
